name: windows

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  schedule:
  - cron: "0 5 * * 1"

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create virtualenv
      run: |
        pip install virtualenv
        virtualenv .env
        .env\Scripts\activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Prepapre MSVC dev environment
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
    - name: Compile blst and build ext (in-place)
      run: |
        cd blst/
        ./build.bat
        cd ..
        mkdir -p ./blst-lib/windows/
        cp ./blst/blst.lib            ./blst-lib/windows/
        cp ./blst/bindings/blst.h     ./blst-lib/
        cp ./blst/bindings/blst.hpp   ./blst-lib/
        cp ./blst/bindings/blst_aux.h ./blst-lib/
        python setup.py build_ext --inplace
    - name: Test with pytest
      run: |
        pytest .
